### ISSUE TITLE
Wait for tools in guest stuck after powerOn 

### ISSUE THREAD

**Issue by yosi1** [dblock/vmwaretasks#20]
Hi all , i hope that this forum is still active. 
I use ESX 5.5 , with windows 7 machine 
i use the example below : 
            using (VMWareVirtualHost virtualHost = new VMWareVirtualHost())
            {
                virtualHost.ConnectToVMWareVIServer("1.1.1.1", "root", "password");
                using (VMWareVirtualMachine virtualMachine = virtualHost.Open(@"[Compellent_External_] yosia_win7_172_23_24_200_1/yosia.vmx"))
                {
                    virtualMachine.PowerOn();
                    virtualMachine.WaitForToolsInGuest();
                    virtualMachine.LoginInGuest("user", "password");
          }

The code power on my machine but then the code stuck and i cant login.

**Comment by dblock** [comment]
Haven't touched this in a while. It's possible that there's more work to be done for ESX 5.5, it's a lot newer than the last one I've used with this project. Take a look at the version of VixCOM installed, unfortunately you have to debug the rest.

**Comment by icnocop** [comment]
The `LoginInGuest` method isn't actually supposed to login the user to the Windows desktop.
The user should already be logged into the desktop before calling the `LogInGuest` method.

**Comment by yosi1** [comment]
Ok my problem was that i didnt install the tools in the machine . 
I figure it out after i install a new machine . 
not all works thanks
